export {default as Header} from './Header/Header.jsx'
export {default as Footer} from './Footer/Footer.jsx'
export {default as Home} from './Home/Home.jsx'
export {default as News} from './News/News.jsx'
export {default as Subteams} from './Subteams/Subteams.jsx'
export {default as Sponsors} from './Sponsors/Sponsors.jsx'