export {default as Home} from './Home/Home.jsx'
export {default as News} from './News/News.jsx'
export {default as OurTeam} from './OurTeam/OurTeam.jsx'
export {default as Sponsors} from './Sponsors/Sponsors.jsx'
export {default as Team} from './Home/Team/Team.jsx'
export {default as HomeSponsors} from './Home/HomeSponsors/HomeSponsors.jsx'